name: Generate Snake

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate-snake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate Snake Image
        run: |
          python generate_snake.py
          
      - name: Upload Snake Image
        uses: actions/upload-artifact@v2
        with:
          name: snake-image
          path: ./snake-image.png
